apiVersion: apps/v1
kind: Deployment
metadata:
  name: fraud-model-deployment
  labels:
    app: fraud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fraud
  template:
    metadata:
      labels:
        app: fraud
    spec:
      containers:
        - name: fraud
          image: slavkostrov/fraud_model:v.0.0.13
          ports:
            - containerPort: 8000
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: fraud-model-secret
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: fraud-model-secret
                  key: AWS_SECRET_ACCESS_KEY
            - name: MLFLOW_S3_ENDPOINT_URL
              valueFrom:
                secretKeyRef:
                  name: fraud-model-secret
                  key: MLFLOW_S3_ENDPOINT_URL
            - name: AWS_S3_ENDPOINT_URL
              valueFrom:
                secretKeyRef:
                  name: fraud-model-secret
                  key: AWS_S3_ENDPOINT_URL
            - name: AWS_DEFAULT_REGION
              valueFrom:
                secretKeyRef:
                  name: fraud-model-secret
                  key: AWS_DEFAULT_REGION
