apiVersion: v1
kind: Secret
metadata:
  name: fraud-model-secret
type: Opaque
data:
  AWS_ACCESS_KEY_ID: ...
  AWS_SECRET_ACCESS_KEY: ...
  MLFLOW_S3_ENDPOINT_URL: ...
  AWS_S3_ENDPOINT_URL: ...
  AWS_DEFAULT_REGION: ...

# kubectl create -f ./secrets.yaml