name: python

on: push

jobs:
  test_env:
    environment: practice_7
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        
    - name: Test env vars for python
      run: | 
        python -c 'import os;print(os.environ);print(os.system("pwd"));print(123456, os.system("ls"))'
        ls -al
      env:
        MLFLOW_S3_ENDPOINT_URL: ${{ secrets.MLFLOW_S3_ENDPOINT_URL }} 
        AWS_S3_ENDPOINT_URL: ${{ secrets.AWS_S3_ENDPOINT_URL }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        MLFLOW_URI: ${{ secrets.MLFLOW_URI }}
        TTTEST: 1
        
    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 .
      continue-on-error: true
      
    - name: Test with pytest
      run: |
        pip install pytest
        pytest ../tests
      continue-on-error: true
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    -
      name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Build and push
      uses: docker/build-push-action@v3
      with:
        push: true
        context: "{{defaultContext}}:fastapi_practice"
        tags: slavkostrov/fraud_model:latest
        
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
