name: python

on: push

jobs:
  test_env:
    environment: practice_7
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        
    - name: Test env vars for python
      run: python -c 'import os;print(os.environ)'
      env:
        ENV_SECRET: ${{ secrets.MLFLOW_S3_ENDPOINT_URL }} 
        REPO_SECRET: ${{ secrets.REPO_SECRET }}
