name: python

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  test_env:
    environment: practice_7
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        
    - name: Test env vars for python
      run: python -c 'import os;print(os.environ)'
      env:
        TTTEST: 1
        
    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 .
      continue-on-error: true
      
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --no-cache-dir --upgrade -r fastapi_practice/requirements.txt
        pip install flake8 pytest mlflow scikit-learn
      
    - name: Pytest summary
      uses: dariocurr/pytest-summary@v1
      env:
        MLFLOW_S3_ENDPOINT_URL: ${{ secrets.MLFLOW_S3_ENDPOINT_URL }} 
        AWS_S3_ENDPOINT_URL: ${{ secrets.AWS_S3_ENDPOINT_URL }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        MLFLOW_URI: ${{ secrets.MLFLOW_URI }}

    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    -
      name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Build and push
      uses: docker/build-push-action@v3
      with:
        push: true
        context: "{{defaultContext}}:fastapi_practice"
        tags: slavkostrov/fraud_model:$GITHUB_REF_NAME
